stefanbuck/awesome-browser-extensions-for-github

- README.md
Chrome extension to display size of each file, download link and an option of copying file contents directly to clipboard
https://chrome.google.com/webstore/detail/github-plus/anlikcnbgdeidpacdbdljnabclhahhmd
> add github-plus extension

- README.md
Chrome extension to let users to automatic merge when the build succeeds on Github.
If you've reviewed a merge request, but the CI builds are still running, it can be annoying to have to wait for them to finish. This way, you don't have to wait for the builds to finish and remember to merge the request manually.
https://chrome.google.com/webstore/detail/octomerge/bcfdlpkdamkbcidkenogbahohlnonebo
> Add Octomerge, a missing button for automatic merge on build succeeds on Github

- README.md
GitHub updated its user interface 14th September, which included this feature!
So we no longer need an extension for it.
> remove GitHub Classifier

- .travis.yml
- README.md
I did 3 things to (hopefully) fix the Travis errors:
1. Added `--alow-redirects` to the `awesome_bot` script so that `301`s don't throw an error.
2. Fixed all the `301`s I found anyway so we'd have a clean slate
3. Fixed/removed all the `404`s I found.
This should clean up tests moving forward. :crossed_fingers:
> Fix awesome bot errors

- README.md
GitHub has changed their markdown rendering (I think it might be [this change](https://githubengineering.com/a-formal-spec-for-github-markdown/), and the `<details>` elements currently don't show the screenshots when expanded.
This change simply adds a blank line before the images inside the `<details>`, so that they actually show up. See the [rich diff](https://github.com/stefanbuck/awesome-browser-extensions-for-github/pull/70/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) to test the changes.
> Fix screenshot rendering

- README.md
[OctoPermalinker](https://github.com/josephfrazier/octopermalinker) is a browser extension that searches GitHub comments/files for links to files on branches, and adds a link to where the branch pointed when the comment/file was made/updated. This helps you avoid following a link that was broken after being posted. For context, here's some discussion about broken GitHub links: [Don't link to line numbers in GitHub](https://news.ycombinator.com/item?id=8046710).
For example, suppose you're looking at a gist that links to a file on the master branch of a repo. At the time the gist was made, the link worked, but if the file gets removed, the link is broken. OctoPermalinker uses the gist creation date to add a permalink that still works. Here are some screencasts demonstrating the difference:
> Add OctoPermalinker

- README.md
>A Chrome and Firefox extension to quickly see your notifications in a popup without leaving the current page.
<details><summary>Screenshot</summary>
</details>
> Adds notifications preview for github

- README.md
Adds [Render Whitespace on GitHub](https://github.com/glebm/render-whitespace-on-github).
<a href="https://github.com/glebm/render-whitespace-on-github"><img src="https://raw.githubusercontent.com/glebm/render-whitespace-on-github/master/icon128.png" width="48" /></a>
> Add Render Whitespace on GitHub

- README.md
Hey, thanks for this awesome list! Want to add [Sourcegraph for GitHub](https://chrome.google.com/webstore/detail/sourcegraph-for-github/dgjhfomjieaadpoljlnidmbgkdffpack) here. The extension adds go-to-definition, find references, and powerful code search to GitHub. 
I added it next to ZenHub since the extension fits in multiple categories (could be repository for jump-to-de and find-references, or it could be search), but let me know if there's a better section to add this.
> Add Sourcegraph for GitHub

- README.md
Refined GitHub have official Firefox addon on AMO, So linking to it. 
Instead of single picture showing all features, RGH have separate image for each features. Better to remove single image or link highlighted features ?
Looks like the linked [RGH safari port](https://github.com/fantattitude/refined-github-safari/) is no longer maintained. [Last commit on May 22, 2016.](https://user-images.githubusercontent.com/10276208/37093208-8fdabe96-2234-11e8-894c-2ab59773d95a.png). Seriously behind upstream, Better to remove it ?
> Link Refined GitHub Firefox addon

- README.md
Hello,
This extension is more relevant to the navigation section than the repository section, I feel. I moved it there.
Thanks for considering!
> Move Markdown Outline Extension from repository to navigation

- README.md
stylize GitHub with a capital 'G' and 'H' in visible text.  Don't modify
some project names like "GithubOriginalStreak" and "github.expandinizr".
> consistently capitalize 'GitHub' in visible text

- README.md
A small extension I made to make it more convenient to view asciinema screencasts on GitHub :slightly_smiling_face:
-----
[View rendered README.md](https://github.com/plibither8/awesome-browser-extensions-for-github/blob/patch-1/README.md)
> Add "asciinema Player for GitHub"

- README.md
Based on issue: #126
-----
[View rendered README.md](https://github.com/tcelestino/awesome-browser-extensions-for-github/blob/docs/screenshot-url/README.md)
> Fix screenshot url in the "What's New on GitHub" extension

- README.md
Add OctoLenses URL for Firefox.
-----
[View rendered README.md](https://github.com/filips123/awesome-browser-extensions-for-github/blob/patch-1/README.md)
> Add OctoLenses URL for Firefox

- README.md
Hi @stefanbuck,
This pull request adds followgithub.org extensions (Chrome and Firefox) in the newsfeed category.
Please let me know if I'm missing anything.
-----
[View rendered README.md](https://github.com/pravj/awesome-browser-extensions-for-github/blob/master/README.md)
> Add follow-github-organization

- README.md
The vs-code icons extension seems to have a firefox version now, which is not yet linked here.
-----
[View rendered README.md](https://github.com/schaafjs/awesome-browser-extensions-for-github/blob/master/README.md)
> Add Firefox URL for vscode-icons

- README.md
Hi, I have an extension that allows users to see the number of lines in text files (or the number of files in folders) without clicking them. 
-----
[View rendered README.md](https://github.com/sheonhan/awesome-browser-extensions-for-github/blob/add-github-peek/README.md)
> Add GitHub peek

- README.md
This extension brings a WYSIWYG editor for GitHub.
-----
[View rendered README.md](https://github.com/gok9ok/awesome-browser-extensions-for-github/blob/master/README.md)
> Add GitHub Writer

- README.md
Semantic Code Reviews is a Chrome extension developed by [explore.dev](https://explore.dev/) to provide reviewers with a guide on the code changes to review and relevant semantic context.
---
[View rendered README.md](https://github.com/explore-dev/awesome-browser-extensions-for-github/blob/master/README.md)
> Add Semantic Code Reviews

- README.md
Thanks for maintaining this awesome list!
This is an extension I've recently published that _marks as viewed_ files in pull requests. At my company we have heaps of autogenerated files in our repository and this extension has been a time saver 😄.
-----
[View rendered README.md](https://github.com/Luismahou/awesome-browser-extensions-for-github/blob/patch-1/README.md)
> Add Autoviewed extension to Pull Requests section

- README.md
- Many extensions with Safari links (Notifier for Github, Github Hovercard, Isometric Contributions, and GitHub Highlight Selected) use the deprecated `.safariextz` method of installing and have not been updated to address these changes. 
- Refined Github now has an [actually maintained port](https://github.com/lautis/refined-github-safari), so we can reverse that part of #98 and add the Safari Extension
-----
[View rendered README.md](https://github.com/jneplokh/awesome-browser-extensions-for-github/blob/master/README.md)
> Update Safari Extension Links

- data.json
This pull request added my browser extension [GitHub Dark Mode](https://github.com/MrWillCom/github-dark-mode).
> Add GitHub Dark Mode

- data.json
Thanks for maintaining this list, the web version is a really nice touch 👌 
This PR adds my extension [GIFs for GitHub](https://github.com/N1ck/gifs-for-github)
> Add GIFs for GitHub extension

- data.json
Hi ! 
I developed an extension to speed up code reviews :wink:
This browser extension allows you to open files in your IDE directly from GitHub, assuming the repository you are working on is cloned on your computer. When a fragment of a file is displayed, your IDE opens the file and puts the cursor at the desired line.
> Add "Open Github file links in IDE"

- data.json
This pull request adds an extension which reverts some of the design changes that were made to the GitHub UI back in June 2020.
> data.json: Add "Old School GitHub" extension

- data.json
At least for now it seems the Chrome extension for Module Linker is no longer available. Reference [Readme Notice](https://github.com/fiatjaf/module-linker#notice) and [Issue](https://github.com/fiatjaf/module-linker/issues/60).
> Remove Chrome Extension for Module Linker

- data.json
Repository was moved from <https://github.com/Katsute/GitHub-Red-Issues> to <https://github.com/KatsuteDev/GitHub-Red-Issues>.
> Update repository for GitHub Red Issues
