stefanbuck/awesome-browser-extensions-for-github

README.md

Saw this extension was missing, does a few things the other extensions do (notifications, tab size) and more, thought it was worth adding.

Add Github Mate

---

README.md

GitHub AST Viewer

---

README.md

Minor English tweak

---

README.md

Add Octo Preview (live markdown preview in comments)

---

README.md

Add Contributors on Github Extension

---

README.md

It would be awesome if it would be merged into the list.

Adding Review on GitHub as browser extension

---

README.md

Hi, some people just have more than 5 cool repositories to show, so I make this https://github.com/onmyway133/github-extended

Add GitHub Extended

---

README.md

Closes #32 
Btw: I've chosen a random position

Add News Feed for GitHub

---

README.md

Add Codecov

---

README.md

Hey Stefan!
Hope you find my add-on a good addition to your awesome-list :)

Add MiniGitHub

---

README.md

Added CoderStats link for GitHub extension

---

README.md

I had lost my extensions and had to dig this one up the hard way. Missing from the list!

Add OctoTern

---

README.md

Add "GitHub Custom Tab Size"

---

README.md

Add Git Git Hooray

---

README.md

https://github.com/duxet/builds-tab

Add Builds Tab for Github

---

README.md

Add OctoDraft

---

README.md

update Categoric image

---

README.md

I build a GitHub extension called [github-file-icon](https://github.com/xxhomey19/github-file-icon)
Hope you like it!

Add github-file-icon

---

README.md

Hi, great list! Hoping you can add my Codeflower extension? It's a code-visualization tool. I put it under miscellaneous. Thanks :)

added Codeflower

---

README.md

https://github.com/Naramsim/GithubOriginalStreak

Add GithubOriginalStreak

---

README.md

https://github.com/andersonba/github-review-filter

add github-review-filter to PullRequest section

---

README.md

[noam3127/GitHub Code Folding](https://github.com/noam3127/github-code-folding)

Add GitHub Code Folding

---

README.md

Being frustrated with GitHub getting unresponsive on big pull request worked on this extension which optimizes the page for a better experience while code review. 
Hope this will be a nice addition to the list.

Added github-turbo-pr

---

README.md

I created the [OctoLenses](https://github.com/rgehan/octolenses-browser-extension/) and could use a little bit of exposure.
I think this extension could help a lot of people, so that would be a great addition IMO.
Thanks!

Add OctoLenses in Miscellaneous

---

README.md

Closes #117
-----
[View rendered README.md](https://github.com/stefanbuck/awesome-browser-extensions-for-github/blob/117/README.md)

Remove Email Extractor & Codecov

---

README.md

-----
[View rendered README.md](https://github.com/dzhavat/awesome-browser-extensions-for-github/blob/add-extension/README.md)

Add Potential changes for GitHub extension

---

README.md

These two extensions do not work anymore.
The first one yields the error:
```
app.js:187 Uncaught TypeError: Cannot read property 'addEventListener' of null
at FileFilter.bindEventListener (app.js:187)
at FileFilter.init (app.js:193)
at app.js:21
at gitHubInjection (app.js:511)
at Object.1../file-filter (app.js:14)
at s (app.js:1)
at e (app.js:1)
at app.js:1
```
The second one yields the error:
```
Uncaught TypeError: $ is not a function
at init (init.js:25)
at init.js:124
at init.js:129
```
The third one yields:
```
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
at PullRequestPage.insertMenu (eval at <anonymous> (chrome-extension://gnpcfigiidmljgiidkhmmcgbfkolnacg/index.bundle.js:184:1), …
```

Remove obsolete PR filter extensions

---

README.md

-----
[View rendered README.md](https://github.com/pomber/awesome-browser-extensions-for-github/blob/patch-1/README.md)

Add Git History

---

README.md

Add Gifhub Pull Requests by @bguzmanrio to the Pull Requests section.

Add Gifhub Pull Requests

---

README.md

Hi, thanks for curating this list! Although my extension is small, I found this useful. is it possible to add? 
-----
[View rendered README.md](https://github.com/banyan/awesome-browser-extensions-for-github/blob/github-story-points/README.md)

Add GitHub Story Points

---

README.md

-----
[View rendered README.md](https://github.com/huchenme/awesome-browser-extensions-for-github/blob/patch-1/README.md)

Add Hacker Tab extension

---

README.md

Fixes #130 🙂
-----
[View rendered README.md](https://github.com/fwouts/awesome-browser-extensions-for-github/blob/patch-1/README.md)

Add PR Monitor

---

README.md

Categoric is more related to the notifications section rather than pull requests.
-----
[View rendered README.md](https://github.com/hkdobrev/awesome-browser-extensions-for-github/blob/patch-1/README.md)

Move Categoric Extension to Notifications

---

README.md

-----
[View rendered README.md](https://github.com/andriyor/awesome-browser-extensions-for-github/blob/master/README.md)

add Awesome Stars

---

README.md

CodeWyng is a browser extension that augments the GitHub UI and provides hover documentation, go-to-definition, and find-references.
http://codewyng.io/
-----
[View rendered README.md](https://github.com/chrismwendt/awesome-browser-extensions-for-github/blob/patch-1/README.md)

Add CodeWyng

---

README.md

-----
[View rendered README.md](https://github.com/aminya/awesome-browser-extensions-for-github/blob/patch-1/README.md)

Fix broken gif

---

README.md

See https://github.com/CodeWyng/codewyng/commit/f3dc6eacc16b47ac04735c4baaaa7cedcc08726a
-----
[View rendered README.md](https://github.com/kidonng/awesome-browser-extensions-for-github/blob/patch-1/README.md)

Fix broken CodeWyng screenshot

---

README.md

-----
[View rendered README.md](https://github.com/kidonng/awesome-browser-extensions-for-github/blob/patch-1/README.md)

Fix broken Enhanced GitHub screenshots

---

README.md

Hey @stefanbuck 
just fixing some typos in the README.
Cheers,
Peter
-----
[View rendered README.md](https://github.com/SpeksForks/awesome-browser-extensions-for-github/blob/main/README.md)

MINOR: fixing typo in README

---

data.json

Hey @stefanbuck 
Spotted another typo 💪️
Peter

Fixing typo

---

README.md
data.json

[View rendered README.md](https://github.com/aeilot/awesome-browser-extensions-for-github/blob/patch-1/README.md)

Add the Safari port of GitHub Dark Mode

---

data.json

Hiya :wave: 
I hope everything is as you need it, else let me know and I can amend :+1: 
My repo is not public, so I used Zenhub's entry as a guide.
Thank you again for maintaining this list :nerd_face: :sunglasses: :smile_cat:

Add Github Saved Filters extension

---

data.json

Add Safari to npmhub, rename it from npm-hub

---

data.json

CodeWyng was renamed to CodeWing https://codewing.dev

CodeWyng was renamed to CodeWing

---

data.json

-----
[View rendered README.md](https://github.com/lebensterben/awesome-browser-extensions-for-github/blob/patch-1/README.md)

Added firefox github-diff-navigattor link

---

data.json

-----
[View rendered README.md](https://github.com/lebensterben/awesome-browser-extensions-for-github/blob/patch-3/README.md)

Added firefox addon link for github-story-points

---

data.json

-----
[View rendered README.md](https://github.com/lebensterben/awesome-browser-extensions-for-github/blob/patch-2/README.md)

Add firefox addon link for github-user-language

---

data.json

Hi. I've created https://github.com/banyan/github-csv-diff to see the diff of csv easily.

Add github-csv-diff extension

---

data.json

update some urls
